__include__: [
  '../dataset/aluminium_detection.yml',
  '../runtime.yml',
  '../base/dataloader_dfine.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
]

output_dir: ./outputs/dfine_hgnetv2_s_all

model: DEIM_MG

DEIM_MG:
  yaml_path: configs\ultralytics-yaml\cfg-improve\module\dfine-s-all.yaml

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0001
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0001
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001


# Increase to search for the optimal ema
epoches: 200 # 120 + 4n

## Our LR-Scheduler
flat_epoch: 98    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
no_aug_epoch: 12

## Our DataAug
train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [4, 98, 188]   # list 

  collate_fn:
    mixup_epochs: [4, 98]
    stop_epoch: 188
    
  total_batch_size: 4
val_dataloader:
  total_batch_size: 4
